import { TorBlockMiddleware } from './tor-block.middleware';

describe('TorBlockMiddleware', () => {
  it('should be defined', () => {
    expect(new TorBlockMiddleware()).toBeDefined();
  });
});

// This file is what automatically generated by NestJS, here you can apply several testing codes if you wish.
